/**
 * For Scraping HTML data from a Notice of Default search on http://www.utahcounty.gov/LandRecords
 * 
 * ------------------------START
 * http://www.utahcounty.gov/LandRecords/DocKoiForm.asp
 * Enter Kind of Instrument (KOI) "ND" //Notice of Default
 * Beginning Recording Date "<TODAYSDATE>" //Search only for today
 * http://www.utahcounty.gov/LandRecords/DocKoi.asp?avKoi=ND&avEntryDate=10%2F02%2F2014&Submit=Search //autogenerated URL
 * html>body>table>tbody>tr>td>table>tbody>tr>td>a //sequence of address of info
 * <a href="document.asp?avEntry=70625&amp;avYear=2014">70625</a>
 * Go to Address
 * http://www.utahcounty.gov/LandRecords/document.asp?avEntry=70625&avYear=2014
 * html>body>table>tbody>tr>td>table>tbody>tr>td>a
 * <a href="PartyName.asp?avname=KANTARIS, DWAYNE">KANTARIS, DWAYNE</a> //STORE NAME
 * Use above Name for
 * http://www.utahcountyonline.org/LandRecords/NameSearchForm.asp
 * Enter Name to search for: "NAME"
 * http://www.utahcountyonline.org/LandRecords/NameSearch.asp?av_name=KANTARIS%2C+DWAYNE&av_valid=%25&Submit=Search
 * Go to Serial# next to Years Valid line with Green text and ellipses 
 * OWNER NAME		SERIAL NUMBER	TAX D	YEARS	PROPERTY ADDRESS //APPEARS ON PAGE
 * KANTARIS, DWAYNE	49:352:0010	 	(150)	2004...	324 E 1000 NORTH - SPANISH FORK //APPEARS ON PAGE
 * html>body>table>tbody>tr>td>table>tbody>tr>td>a
 * <a href="property.asp?av_serial=493520010003">49:352:0010</a> //STORE SERIAL #
 * http://www.utahcounty.gov/LandRecords/Property.asp?av_serial=493520010003 //URL OF SERIAL # FOR PAGE
 * Property Address:  324 E 1000 NORTH - SPANISH FORK //APPEARS ON PAGE
 * Mailing Address: 522 N 600 E OREM, UT 84097-4208 //APPEARS ON PAGE
 * html>body>table>tbody>tr>td>table>tbody>tr>td>table>tbody>tr>td>strong
 * <strong>Property Address:</strong>
 * html>body>table>tbody>tr>td>table>tbody>tr>td>table>tbody>tr>td>(text)
 * &nbsp; 324 E 1000 NORTH - SPANISH FORK //STORE AS PROPERTY ADDRESS
 * html>body>table>tbody>tr>td>table>tbody>tr>td>table>tbody>tr>td>strong
 * <strong>Mailing Address:</strong>
 * html>body>table>tbody>tr>td>table>tbody>tr>td>table>tbody>tr>td>(text)
 *  " 522 N 600 E  OREM, UT 84097-4208" //STORE AS MAILING ADDRESS
 * html>body>table>tbody>tr>td>table>tbody>tr>td>select#jumpMenu.forcestyle>option
 * <option value="Abstract.asp?av_serial=49:352:0010">Abstract</option>
 * http://www.utahcounty.gov/LandRecords/Abstract.asp?av_serial=49:352:0010 //STORE ALL HTML
 * html>body>table>tbody>tr>td>em.italic>table>tbody>tr
 * Need any number $ on far right table CONSIDERATION, SATISFACTION, TIE ENTRY NO
 * Get left side for values other than 0, GRANTOR, GRANTEE, COMMENTS //STORE ALL GRANTOR/GRANTEE INFO
 * ------------------------END
 * 
 * http://jsoup.org/apidocs/ //Documentation for Java HTML parser API
 * https://github.com/PhotonPhighter/NODScraper //Location of SOURCE CODE
 */

package nodscraper;

import java.io.IOException;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 * @author Ali M (PhotonPhighter/Admiral Nero the XCIV)
 */

public class Main{
	/**
	 * ARGGIMOOOLIDOO NOTHING TO SEE HERE
	 */
	public Main(){
		//Auto-generated constructor stub, exists for reasons and stuff, not really
	}//end of Main constructor
	/**
	 * @param args
	 */
	public static void main(String[] args) throws IOException{
		//?? Experimental ??
		String MM = "10";	//month you want to start search at
		String DD = "01";	//day you want to start search at
		String YYYY = "2014";	//year you want to start search at
		String stringSiteURLForMainSearch = "http://www.utahcounty.gov/LandRecords/DocKoi.asp?avKoi=ND&avEntryDate="+MM+"%2F"+DD+"%2F"+YYYY+"&submit=Search";	//the URL of the page including date
		print("Fetching current ND records from Date %s/%s/%s\n <%s>...", MM, DD, YYYY, stringSiteURLForMainSearch);	//print current action
		try{
			Document documentCompletedSearch = Jsoup.connect(stringSiteURLForMainSearch+MM+"%2F"+DD+"%2F"+YYYY+"&submit=Search").get();	//connect to url
			Elements linksOnCompletedSearch = documentCompletedSearch.select("a[href]");	//get all the links in the current document and put them in a list
			linksOnCompletedSearch.remove(0);	//remove first link, as it is superfluous
			for (int i=0; i<4; i++){	//iterate to remove the bottom 4 links, as they are superfluous
				linksOnCompletedSearch.remove(linksOnCompletedSearch.size()-1);	//just said it, right there above
			}//end of for loop
			print("\nRecords: " + linksOnCompletedSearch.size());	//print how many links are left in the list from completed search
			for (Element link : linksOnCompletedSearch){	//for every link element in the list of links do what's below
				String stringFileEntryNumber = trim(link.text(), 35);	//collect the entry number for each case
				String stringURLForFileEntryNumber = link.attr("abs:href");	//collect the URL for connecting to particular entry number's page
				//print("*  <%s>", stringURLForFileEntryNumber);	//ignore, for debugging
				print("(%s)", stringFileEntryNumber);	//print out the gathered entry number
				Document documentURLForEntryNumber = Jsoup.connect(stringURLForFileEntryNumber).get();	//connect to the URL for the entry number's page, to get the name
				Elements linksOnEntryNumberPage = documentURLForEntryNumber.select("a[href]");	//get all the links listed on entry number page
				print ("Links: " + linksOnEntryNumberPage.size());	//ignore, for debugging
				/**
				 * below are different cases for the number of links on entry number page, as it varies
				 */
				if (linksOnEntryNumberPage.size() < 9){	//if there are less than 9 links on entry number page, do below
					linksOnEntryNumberPage.remove(0);	//remove first link as it is superfluous
					linksOnEntryNumberPage.remove(0);	//remove second link "
					for (int i=0; i<5; i++){	//iterate to remove the bottom 5 links, as they are also superfluous
						linksOnEntryNumberPage.remove(linksOnEntryNumberPage.size()-1);	//said in line above
					}//end of nested for loop
				}//end of if statement
				if (linksOnEntryNumberPage.size() == 9){	//additional case, see above
					linksOnEntryNumberPage.remove(0);
					linksOnEntryNumberPage.remove(0);
					for (int i=0; i<5; i++){
						linksOnEntryNumberPage.remove(linksOnEntryNumberPage.size()-1);
					}//end of nested for loop
				}//end of if statement
				if (linksOnEntryNumberPage.size() > 9){	//additional case, see above
					linksOnEntryNumberPage.remove(0);
					linksOnEntryNumberPage.remove(0);
					for (int i=0; i<5; i++){
						linksOnEntryNumberPage.remove(linksOnEntryNumberPage.size()-1);
					}//end of nested for loop
					linksOnEntryNumberPage.remove(linksOnEntryNumberPage.size()-2);
				}//end of else statement
				String stringURLforGranteeName = linksOnEntryNumberPage.attr("abs:href");	//get the URL containing the Grantee's name
				String stringGranteeName = trim(linksOnEntryNumberPage.text(), 35);	//get the actual name out of the link
				for (Element link2 : linksOnEntryNumberPage){	//for all the links left, do below
					stringURLforGranteeName = link2.attr("abs:href");	//??Wait, why?
					print("<%s>", stringURLforGranteeName);	//ignore, for debugging
					print("(%s)\n", stringGranteeName);	//print the Grantee's name, going to use it for search later
				}//end of nested for loop
			}//end of for loop
		}//end of try statement
		catch (IOException e){
			e.printStackTrace();	//print stack trace if you fuck something up
		}//end of catch statement
	}//end of Main method
	
	private static void print(String msg, Object... args){
		System.out.println(String.format(msg,  args));	//useful method for printing to console
	}//end of print method
	
	private static String trim(String s, int width){
		if (s.length() > width)
			return s.substring(0, width-1)+".";
		else
			return s;	//useful method for trimming Strings for links list
	}//end of trim method
}//end of Main class